config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :mgmts
	resources :abouts
	resources :homes
	resources :menus
  resources :events
	resources :users
	post '/register', to: 'registers#email'
	get '/login', to: 'users#login'
	patch '/login', to: 'users#verify'
	get '/logout', to: 'users#logout'
	post '/login', to: 'users#verify'
	get '/mgmt', to: 'events#index'
	get '/', to: 'front_end#index'
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate
	layout "mgmts.html.erb"
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/1/edit
  def edit
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:food1, :food2, :food3, :food4, :food5, :food1Desc, :food2Desc, :food3Desc, :food4Desc, :food5Desc)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_beer.html.erb
<select id="beerSelect">
	<option value="beer1_1">Beer 1</option>
	<option value="beer1_2">Beer 2</option>
	<option value="beer1_3">Beer 3</option>
	<option value="beer1_4">Beer 4</option>
	<option value="beer1_5">Beer 5</option>
	<option value="beer2_1">Beer 6</option>
	<option value="beer2_2">Beer 7</option>
	<option value="beer2_3">Beer 8</option>
	<option value="beer2_4">Beer 9</option>
	<option value="beer2_5">Beer 10</option>
	<option value="beer3_1">Beer 11</option>
	<option value="beer3_2">Beer 12</option>
	<option value="beer3_3">Beer 13</option>
	<option value="beer3_4">Beer 14</option>
	<option value="beer3_5">Beer 15</option>
</select>

<div id="beer1_1">
	<%= f.label "Beer 1 Name", class: ''%>
	<%= f.text_field :beer1_1, class: ''%>

	<%= f.label "Beer 1 Price", class: ''%>
	<%= f.text_field :beer1_1_price, class: ''%>

	<%= f.label "Beer 1 Description", class: ''%>
	<%= f.text_area :beer1_1Desc, class: ''%>
</div>
<div id="beer1_2" style="display: none">
	<%= f.label "Beer 2 Name", class: ''%>
	<%= f.text_field :beer1_2, class: ''%>

	<%= f.label "Beer 2 Price", class: ''%>
	<%= f.text_field :beer1_2_price, class: ''%>

	<%= f.label "Beer 2 Description", class: ''%>
	<%= f.text_area :beer1_2Desc, class: ''%>
</div>

<div id="beer1_3" style="display: none">
	<%= f.label "Beer 3 Name", class: ''%>
	<%= f.text_field :beer1_3, class: ''%>

	<%= f.label "Beer 3 Price", class: ''%>
	<%= f.text_field :beer1_3_price, class: ''%>

	<%= f.label "Beer 3 Description", class: ''%>
	<%= f.text_area :beer1_3Desc, class: ''%>
</div>

<div id="beer1_4" style="display: none">
	<%= f.label "Beer 4 Name", class: ''%>
	<%= f.text_field :beer1_4, class: ''%>

	<%= f.label "Beer 4 Price", class: ''%>
	<%= f.text_field :beer1_4_price, class: ''%>

	<%= f.label "Beer 4 Description", class: ''%>
	<%= f.text_area :beer1_4Desc, class: ''%>
</div>

<div id="beer1_5" style="display: none">
	<%= f.label "Beer 5 Name", class: ''%>
	<%= f.text_field :beer1_5, class: ''%>

	<%= f.label "Beer 5 Price", class: ''%>
	<%= f.text_field :beer1_5_price, class: ''%>

	<%= f.label "Beer 5 Description", class: ''%>
	<%= f.text_area :beer1_5Desc, class: ''%>
</div>

<div id="beer2_1" style="display: none">
	<%= f.label "Beer 6 Name", class: ''%>
	<%= f.text_field :beer2_1, class: ''%>

	<%= f.label "Beer 6 Price", class: ''%>
	<%= f.text_field :beer2_1_price, class: ''%>

	<%= f.label "Beer 6 Description", class: ''%>
	<%= f.text_area :beer2_1Desc, class: ''%>
</div>

<div id="beer2_2" style="display: none">
	<%= f.label "Beer 7 Name", class: ''%>
	<%= f.text_field :beer2_2, class: ''%>

	<%= f.label "Beer 7 Price", class: ''%>
	<%= f.text_field :beer2_2_price, class: ''%>

	<%= f.label "Beer 7 Description", class: ''%>
	<%= f.text_area :beer2_2Desc, class: ''%>
</div>

<div id="beer2_3" style="display: none">
	<%= f.label "Beer 8 Name", class: ''%>
	<%= f.text_field :beer2_3, class: ''%>

	<%= f.label "Beer 8 Price", class: ''%>
	<%= f.text_field :beer2_3_price, class: ''%>

	<%= f.label "Beer 8 Description", class: ''%>
	<%= f.text_area :beer2_3Desc, class: ''%>
</div>

<div id="beer2_4" style="display: none">
	<%= f.label "Beer 9 Name", class: ''%>
	<%= f.text_field :beer2_4, class: ''%>

	<%= f.label "Beer 9 Price", class: ''%>
	<%= f.text_field :beer2_4_price, class: ''%>

	<%= f.label "Beer 9 Description", class: ''%>
	<%= f.text_area :beer2_4Desc, class: ''%>
</div>

<div id="beer2_5" style="display: none">
	<%= f.label "Beer 10 Name", class: ''%>
	<%= f.text_field :beer2_5, class: ''%>

	<%= f.label "Beer 10 Price", class: ''%>
	<%= f.text_field :beer2_5_price, class: ''%>

	<%= f.label "Beer 10 Description", class: ''%>
	<%= f.text_area :beer2_5Desc, class: ''%>
</div>

<div id="beer3_1" style="display: none">
	<%= f.label "Beer 11 Name", class: ''%>
	<%= f.text_field :beer3_1, class: ''%>

	<%= f.label "Beer 11 Price", class: ''%>
	<%= f.text_field :beer3_1_price, class: ''%>

	<%= f.label "Beer 11 Description", class: ''%>
	<%= f.text_area :beer3_1Desc, class: ''%>
</div>

<div id="beer3_2" style="display: none">
	<%= f.label "Beer 12 Name", class: ''%>
	<%= f.text_field :beer3_2, class: ''%>

	<%= f.label "Beer 12 Price", class: ''%>
	<%= f.text_field :beer3_2_price, class: ''%>

	<%= f.label "Beer 12 Description", class: ''%>
	<%= f.text_area :beer3_2Desc, class: ''%>
</div>

<div id="beer3_3" style="display: none">
	<%= f.label "Beer 13 Name", class: ''%>
	<%= f.text_field :beer3_3, class: ''%>

	<%= f.label "Beer 13 Price", class: ''%>
	<%= f.text_field :beer3_3_price, class: ''%>

	<%= f.label "Beer 13 Description", class: ''%>
	<%= f.text_area :beer3_3Desc, class: ''%>
</div>

<div id="beer3_4" style="display: none">
	<%= f.label "Beer 14 Name", class: ''%>
	<%= f.text_field :beer3_4, class: ''%>

	<%= f.label "Beer 14 Price", class: ''%>
	<%= f.text_field :beer3_4_price, class: ''%>

	<%= f.label "Beer 14 Description", class: ''%>
	<%= f.text_area :beer3_4Desc, class: ''%>
</div>

<div id="beer3_5" style="display: none">
	<%= f.label "Beer 15 Name", class: ''%>
	<%= f.text_field :beer3_5, class: ''%>

	<%= f.label "Beer 15 Price", class: ''%>
	<%= f.text_field :beer3_5_price, class: ''%>

	<%= f.label "Beer 15 Description", class: ''%>
	<%= f.text_area :beer3_5Desc, class: ''%>
</div>

app/views/menus/_food.html.erb
<select id="foodSelect">
	<option id="food1">Food 1</option>
	<option id="food2">Food 2</option>
	<option id="food3">Food 3</option>
	<option id="food4">Food 4</option>
	<option id="food5">Food 5</option>
</select>

<div id="food1">
	<%= f.label "Food 1 Name", class: ''%>
	<%= f.text_field :food1, class: ''%>

	<%= f.label "Food 1 Price", class: ''%>
	<%= f.text_field :food1_price, class: ''%>

	<%= f.label "Food 1 Description", class: ''%>
	<%= f.text_area :food1Desc, class: ''%>
</div>

<div id="food2" style="display: none">
	<%= f.label "Food 2 Name", class: ''%>
	<%= f.text_field :food2, class: ''%>

	<%= f.label "Food 2 Price", class: ''%>
	<%= f.text_field :food2_price, class: ''%>

	<%= f.label "Food 2 Description", class: ''%>
	<%= f.text_area :food2Desc, class: ''%>
</div>

<div id="food3" style="display: none">
	<%= f.label "Food 3 Name", class: ''%>
	<%= f.text_field :food3, class: ''%>

	<%= f.label "Food 3 Price", class: ''%>
	<%= f.text_field :food3_price, class: ''%>

	<%= f.label "Food 3 Description", class: ''%>
	<%= f.text_area :food3Desc, class: ''%>
</div>

<div id="food4" style="display: none">
	<%= f.label "Food 4 Name", class: ''%>
	<%= f.text_field :food4, class: ''%>

	<%= f.label "Food 4 Price", class: ''%>
	<%= f.text_field :food4_price, class: ''%>

	<%= f.label "Food 4 Description", class: ''%>
	<%= f.text_area :food4Desc, class: ''%>
</div>

<div id="food5" style="display: none">
	<%= f.label "Food 5 Name", class: ''%>
	<%= f.text_field :food5, class: ''%>

	<%= f.label "Food 5 Price", class: ''%>
	<%= f.text_field :food5_price, class: ''%>

	<%= f.label "Food 5 Description", class: ''%>
	<%= f.text_area :food5Desc, class: ''%>
</div>

app/views/menus/_form.html.erb
<%= form_for(menu) do |f| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<h5>Select category</h5>
	<select id="headSelect">
		<option selected>food</option>
		<option>wine</option>
		<option>beer</option>
	</select>
	<br>
	<hr>
	<div id="foodDiv">
		<h5>Select food item</h5>
		<%= render 'food', menu: @menu, f: f %>
	</div>

	<div id="beerDiv" style="display: none">
		<h5>Select beer item</h5>
		<%= render 'beer', menu: @menu, f: f %>
	</div>	

	<div id="wineDiv" style="display: none">
		<h5>Select wine item</h5>
		<%= render 'wine', menu: @menu, f: f %>
	</div>	

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/_wine.html.erb
<select id="wineSelect">
	<option value="wine1_1">Wine 1</option>
	<option value="wine1_2">Wine 2</option>
	<option value="wine1_3">Wine 3</option>
	<option value="wine1_4">Wine 4</option>
	<option value="wine1_5">Wine 5</option>
	<option value="wine2_1">Wine 6</option>
	<option value="wine2_2">Wine 7</option>
	<option value="wine2_3">Wine 8</option>
	<option value="wine2_4">Wine 9</option>
	<option value="wine2_5">Wine 10</option>
	<option value="wine3_1">Wine 11</option>
	<option value="wine3_2">Wine 12</option>
	<option value="wine3_3">Wine 13</option>
	<option value="wine3_4">Wine 14</option>
	<option value="wine3_5">Wine 15</option>
</select>

<div id="wine1_1">
	<%= f.label "Wine 1 Name", class: ''%>
	<%= f.text_field :wine1_1, class: ''%>

	<%= f.label "Wine 1 Price", class: ''%>
	<%= f.text_field :wine1_1_price, class: ''%>

	<%= f.label "Wine 1 Description", class: ''%>
	<%= f.text_area :wine1_1Desc, class: ''%>
</div>
<div id="wine1_2" style="display: none">
	<%= f.label "Wine 2 Name", class: ''%>
	<%= f.text_field :wine1_2, class: ''%>

	<%= f.label "Wine 2 Price", class: ''%>
	<%= f.text_field :wine1_2_price, class: ''%>

	<%= f.label "Wine 2 Description", class: ''%>
	<%= f.text_area :wine1_2Desc, class: ''%>
</div>

<div id="wine1_3" style="display: none">
	<%= f.label "Wine 3 Name", class: ''%>
	<%= f.text_field :wine1_3, class: ''%>

	<%= f.label "Wine 3 Price", class: ''%>
	<%= f.text_field :wine1_3_price, class: ''%>

	<%= f.label "Wine 3 Description", class: ''%>
	<%= f.text_area :wine1_3Desc, class: ''%>
</div>

<div id="wine1_4" style="display: none">
	<%= f.label "Wine 4 Name", class: ''%>
	<%= f.text_field :wine1_4, class: ''%>

	<%= f.label "Wine 4 Price", class: ''%>
	<%= f.text_field :wine1_4_price, class: ''%>

	<%= f.label "Wine 4 Description", class: ''%>
	<%= f.text_area :wine1_4Desc, class: ''%>
</div>

<div id="wine1_5" style="display: none">
	<%= f.label "Wine 5 Name", class: ''%>
	<%= f.text_field :wine1_5, class: ''%>

	<%= f.label "Wine 5 Price", class: ''%>
	<%= f.text_field :wine1_5_price, class: ''%>

	<%= f.label "Wine 5 Description", class: ''%>
	<%= f.text_area :wine1_5Desc, class: ''%>
</div>

<div id="wine2_1" style="display: none">
	<%= f.label "Wine 6 Name", class: ''%>
	<%= f.text_field :wine2_1, class: ''%>

	<%= f.label "Wine 6 Price", class: ''%>
	<%= f.text_field :wine2_1_price, class: ''%>

	<%= f.label "Wine 6 Description", class: ''%>
	<%= f.text_area :wine2_1Desc, class: ''%>
</div>

<div id="wine2_2" style="display: none">
	<%= f.label "Wine 7 Name", class: ''%>
	<%= f.text_field :wine2_2, class: ''%>

	<%= f.label "Wine 7 Price", class: ''%>
	<%= f.text_field :wine2_2_price, class: ''%>

	<%= f.label "Wine 7 Description", class: ''%>
	<%= f.text_area :wine2_2Desc, class: ''%>
</div>

<div id="wine2_3" style="display: none">
	<%= f.label "Wine 8 Name", class: ''%>
	<%= f.text_field :wine2_3, class: ''%>

	<%= f.label "Wine 8 Price", class: ''%>
	<%= f.text_field :wine2_3_price, class: ''%>

	<%= f.label "Wine 8 Description", class: ''%>
	<%= f.text_area :wine2_3Desc, class: ''%>
</div>

<div id="wine2_4" style="display: none">
	<%= f.label "Wine 9 Name", class: ''%>
	<%= f.text_field :wine2_4, class: ''%>

	<%= f.label "Wine 9 Price", class: ''%>
	<%= f.text_field :wine2_4_price, class: ''%>

	<%= f.label "Wine 9 Description", class: ''%>
	<%= f.text_area :wine2_4Desc, class: ''%>
</div>

<div id="wine2_5" style="display: none">
	<%= f.label "Wine 10 Name", class: ''%>
	<%= f.text_field :wine2_5, class: ''%>

	<%= f.label "Wine 10 Price", class: ''%>
	<%= f.text_field :wine2_5_price, class: ''%>

	<%= f.label "Wine 10 Description", class: ''%>
	<%= f.text_area :wine2_5Desc, class: ''%>
</div>

<div id="wine3_1" style="display: none">
	<%= f.label "Wine 11 Name", class: ''%>
	<%= f.text_field :wine3_1, class: ''%>

	<%= f.label "Wine 11 Price", class: ''%>
	<%= f.text_field :wine3_1_price, class: ''%>

	<%= f.label "Wine 11 Description", class: ''%>
	<%= f.text_area :wine3_1Desc, class: ''%>
</div>

<div id="wine3_2" style="display: none">
	<%= f.label "Wine 12 Name", class: ''%>
	<%= f.text_field :wine3_2, class: ''%>

	<%= f.label "Wine 12 Price", class: ''%>
	<%= f.text_field :wine3_2_price, class: ''%>

	<%= f.label "Wine 12 Description", class: ''%>
	<%= f.text_area :wine3_2Desc, class: ''%>
</div>

<div id="wine3_3" style="display: none">
	<%= f.label "Wine 13 Name", class: ''%>
	<%= f.text_field :wine3_3, class: ''%>

	<%= f.label "Wine 13 Price", class: ''%>
	<%= f.text_field :wine3_3_price, class: ''%>

	<%= f.label "Wine 13 Description", class: ''%>
	<%= f.text_area :wine3_3Desc, class: ''%>
</div>

<div id="wine3_4" style="display: none">
	<%= f.label "Wine 14 Name", class: ''%>
	<%= f.text_field :wine3_4, class: ''%>

	<%= f.label "Wine 14 Price", class: ''%>
	<%= f.text_field :wine3_4_price, class: ''%>

	<%= f.label "Wine 14 Description", class: ''%>
	<%= f.text_area :wine3_4Desc, class: ''%>
</div>

<div id="wine3_5" style="display: none">
	<%= f.label "Wine 15 Name", class: ''%>
	<%= f.text_field :wine3_5, class: ''%>

	<%= f.label "Wine 15 Price", class: ''%>
	<%= f.text_field :wine3_5_price, class: ''%>

	<%= f.label "Wine 15 Description", class: ''%>
	<%= f.text_area :wine3_5Desc, class: ''%>
</div>

app/views/menus/edit.html.erb
<div class="row">
	<div class="col s12 m12 l12">
		<h1>Menu Section</h1>
		<div class="card-panel">
			<%= render 'form', menu: @menu %>
		</div>
	</div>
</div>
<script type="application/javascript">
	document.addEventListener("turbolinks:load", function() {
		$('select').select2();
		$('selec').select2();
	});
</script>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', edit_menu_path(@menu) %> |