config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :mgmts
	resources :abouts
	resources :homes
	resources :menus
  resources :events
	resources :users
	post '/register', to: 'registers#email'
	get '/login', to: 'users#login'
	patch '/login', to: 'users#verify'
	get '/logout', to: 'users#logout'
	post '/login', to: 'users#verify'
	get '/mgmt', to: 'events#index'
	get '/', to: 'front_end#index'
end

app/models/mgmt.rb
class Mgmt < ApplicationRecord
end

app/controllers/mgmts_controller.rb
class MgmtsController < ApplicationController
  before_action :set_mgmt, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_time)
    end

end

app/helpers/mgmts_helper.rb
module MgmtsHelper
end

app/views/mgmts/_form.html.erb
<%= form_for(mgmt) do |f| %>
  <% if mgmt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mgmt.errors.count, "error") %> prohibited this mgmt from being saved:</h2>

      <ul>
      <% mgmt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mgmts/edit.html.erb
<h1>Editing Mgmt</h1>

<%= render 'form', mgmt: @mgmt %>

<%= link_to 'Show', @mgmt %> |
<%= link_to 'Back', mgmts_path %>

app/views/mgmts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mgmts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mgmts.each do |mgmt| %>
      <tr>
        <td><%= link_to 'Show', mgmt %></td>
        <td><%= link_to 'Edit', edit_mgmt_path(mgmt) %></td>
        <td><%= link_to 'Destroy', mgmt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mgmt', new_mgmt_path %>

app/views/mgmts/new.html.erb
<h1>New Mgmt</h1>

<%= render 'form', mgmt: @mgmt %>

<%= link_to 'Back', mgmts_path %>

app/views/mgmts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mgmt_path(@mgmt) %> |
<%= link_to 'Back', mgmts_path %>