config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :mgmts
	resources :abouts
	resources :homes
	resources :menus
  resources :events
	resources :users
	post '/register', to: 'registers#email'
	get '/login', to: 'users#login'
	patch '/login', to: 'users#verify'
	get '/logout', to: 'users#logout'
	post '/login', to: 'users#verify'
	get '/mgmt', to: 'events#index'
	get '/', to: 'front_end#index'
end

app/models/about.rb
class About < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate
	layout "mgmts.html.erb"
  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/1/edit
  def edit
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:title_1, :content_1, :title_2, :content_2, :title_3, :content_3, :title_4, :content_4, :title_5, :content_5, :title_6, :content_6)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_form.html.erb
<%= form_for(about) do |f| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	<%= f.label :title_1, class: '' %>
	<%= f.text_field :title_1, class: '' %>
	<%= f.label :content_1, class: '' %>
	<%= f.text_field :content_1, class: '' %>

	<%= f.label :title_2, class: '' %>
	<%= f.text_field :title_2, class: '' %>
	<%= f.label :content_2, class: '' %>
	<%= f.text_field :content_2, class: '' %>

	<%= f.label :title_3, class: '' %>
	<%= f.text_field :title_3, class: '' %>
	<%= f.label :content_3, class: '' %>
	<%= f.text_field :content_3, class: '' %>

	<%= f.label :title_4, class: '' %>
	<%= f.text_field :title_4, class: '' %>
	<%= f.label :content_4, class: '' %>
	<%= f.text_field :content_4, class: '' %>

	<%= f.label :title_5, class: '' %>
	<%= f.text_field :title_5, class: '' %>
	<%= f.label :content_5, class: '' %>
	<%= f.text_field :content_5, class: '' %>
	
	<%= f.label :title_6, class: '' %>
	<%= f.text_field :title_6, class: '' %>
	<%= f.label :content_6, class: '' %>
	<%= f.text_field :content_6, class: '' %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<div class="row">
	<div class="col s12 m12 l12">
		<h1>About Tab</h1>
		<div class="card-panel">
			<%= render 'form', about: @about %>
		</div>
	</div>
</div>

app/views/abouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>About Admin Section</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abouts.each do |about| %>
      <tr>
        <td>Click <%= link_to 'here', edit_about_path(about) %> to edit the about section.</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', edit_about_path(@about) %> |